name: zammad
description: Zammad is a web based open source helpdesk/customer support system
homepage: https://zammad.org
notifications: false
targets:
  debian-9:
    dependencies:
      - curl
      - elasticsearch
      - nginx|apache2
      - postgresql|mariadb-server|sqlite
before:
  - contrib/packager.io/before.sh
after:
  - contrib/packager.io/after.sh
env:
  - RAILS_ENV=production
  - ZAMMAD_BIND_IP=127.0.0.1
  - ZAMMAD_RAILS_PORT=3000
  - ZAMMAD_WEBSOCKET_PORT=6042
services:
  - postgres
after_install: contrib/packager.io/postinstall.sh
